---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age14fwpkypy6tepfxazfkpvmdh5e7cx6jgmqk7nmlccafecvhxjyccsswpzpj"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age14fwpkypy6tepfxazfkpvmdh5e7cx6jgmqk7nmlccafecvhxjyccsswpzpj"
stores:
  yaml:
    indent: 2
