# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:hF54bUWs9CR23QGtjgA//NKnldTXIZNvtzePNQ38AUW0rHmyo8f9Sw==,iv:OzL/ZnID1XCk8JjPza/bvZZ5QEU1a+dDPaFzKtkmv5M=,tag:oELqR0E1XRr7qRuU80yt8g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14fwpkypy6tepfxazfkpvmdh5e7cx6jgmqk7nmlccafecvhxjyccsswpzpj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNjVsU0gwandpckhoSjJG
        SEJYMDNEZnhZRUFZT1QybXI2VDYwb3lGWjFnCmZhRGxGSWhtK0RZbjlhSm5aWW01
        RkpKV0VKMFluOVYyZFhoZnJrNTJZNmcKLS0tIEtvbGVkemNSdHlzZTQweUtXcFBC
        YVRLREFodVJLMU42V3dNV0dNN3M0bzAKqpjkwGRunXE1QisV39xih92LfW6HUNjn
        sjuU9vApYUEi67Z+4EL6XgE1utfIoHw+2JOKZZgMoJ/lXqmDhOtniA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T04:32:22Z"
  mac: ENC[AES256_GCM,data:u3pAsTOLOulfJNeM7yKQ9IU6qUUP2U1t6ydzQGNLytXLn8gaDgpWFRt7vmmf072U2QxCeFa3ueHy68Q0Nh4LRladWA0krmK/A5DSHX2PhDhv0y7dT6jQTGQV7ZvT+FdRhhkj7cFcMeRGsA2HGC5eFV8InqDFF7jefLu06HxWJ9Q=,iv:uKo2oyLQSvCGyLBkowKYc0fSSNm/UR4EatV9oWbIQhU=,tag:mH0SHQR5424bmIAn3DxMaA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
