apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:jwGVqq2hetAE74diNeAyl2F0IU/hS1vo17X+O2NCSW6XbiwrzPnD+oyWMplumJDeBJYpsTKhw6Ll36JHg1gSRDmxcwDGKLppNBA=,iv:G7P0mCMKSxgJmE4izWa02XW/WMgu70TTJHT6bWPxN6A=,tag:Nlv5CMDLYNTTNRHwCUWesQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14fwpkypy6tepfxazfkpvmdh5e7cx6jgmqk7nmlccafecvhxjyccsswpzpj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXanlOb2FXY3N4ck9KUG41
        U0I3WDFBRU53Z0YzU2JhTWJuT0hrZlRSMWtzClRCMTRQdERGKzlxVWJodVYveUpu
        M0g1T09Qd1NZVG9QQThaQzk0QWdlbEUKLS0tIHdoMjIrRkpjWE1VdnZoTGhFT1Jy
        WFNRVms5UlpJUERSOGh2UFRBckl5d2MKh4uABK5FztVuJi0Ci337iCgb6edwQEpO
        /9gwbETdsvzcvHwQX2BegEdRBvldCZhmSoteRGXKfEflZrCHG3AXFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-12T23:05:22Z"
  mac: ENC[AES256_GCM,data:U/sB/5d8HAunNjEE8utFAl1cNLna7ehOIXSmOyO8AzTkk4/FYJPzx8/B5XI9LfCIRGQ0hSmCweSnErdUs9lYuMxsbde0uluGvv/MnBdAnm8uChrz3sb/GrzmtlWsNsM42VyGy631vEs0H1hxoRUodwWJlx8ZT7zJzkpg2rwNKuU=,iv:FgD8dvabV3gVNqVWHAsycfplswHNSUV4OpoYo3DOMik=,tag:jTyEU4/9BFypOCJ+J8efGw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
