apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:HjjEkdnToNydEOXkivVghj5p3fjgIXZ7dbcBvpgcu0889VPwy6dudQk44V1HDLrQuBdyxpu8mJAvW4++7ey5iuBYEvDtpFn/nEQ=,iv:zca2+CG1jmghiTKOLFiugqjmPXw0hcAoRzrMG33HIKY=,tag:Q8LK8Lt3om8ZrTOoJI7qWQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14fwpkypy6tepfxazfkpvmdh5e7cx6jgmqk7nmlccafecvhxjyccsswpzpj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbFg1L1drTklJS3BYc3g0
        dkVvQ3lUclhEYS9oNkVlWXhRVGh2eXc3QWhnCnduZzBMQ0trM2RYcTFFWHdHV2pX
        aXptQk5SVndvVTRaZVB1NUVtU005MFUKLS0tIEgzeU44VnZoVlcwK2VWOEJUaTdl
        NkhlRWlFZkZMaUxoTDIzR2ZTWlV2UmcKR8QvgPHQdynnCHBZiWX3sdeRpLjGeTun
        b/rJ653EPjl60SjwpvCFHNqVjwrdia1uu6v8M/zUyR4sb/03P1mk6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-14T14:53:29Z"
  mac: ENC[AES256_GCM,data:vMEtuWPUfRQI/phmOCGe82W9lq8+7wyrBkNnpcUH0mEfi68/fT+z5qtxhnmyyoHEYirAorEC3Lc96uZbDDpspMJuM4D/Mt+/fv0t6hkj81ompblwElcrWfhBREzyHj9IAnBnnwSwQ22orUjJfHcjWJG3Kk+pnlpr/dGCnj8qi1s=,iv:dzd6umr86mHBw5v1dgU2nINsPwuF5B+yHsNAeIgsWkM=,tag:koEV+nYDbRFzEqCeeZ/FMQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
