apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:DS92Kh1Bk3kAyz5ZGEQ4k9noiscGrSAkbHJ6k7LdymgL1NlrVGoTeS9J9PKvpaBShtrFo1eBq+9ODaOsh7ShpOePGurU0MXdJxM=,iv:5zZAa3vl5uohi/auj00swxCRXKluauoX714Hh6jTCko=,tag:wmPGv7pNoA9HneSAzw8lcw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14fwpkypy6tepfxazfkpvmdh5e7cx6jgmqk7nmlccafecvhxjyccsswpzpj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZURZSlo5TjkveGp3VW9T
        dy85WVpkVmRtUHR5M3B1eUVwaFRXd01CSDFvClo1WHVyeTViZXpaSk5seGdqdi9W
        aHBLSDF4OHNrSC90V3U5Qk5FeC9PblUKLS0tIENmeTRaVHlFMTNub1RwSmpiUE1E
        WE5SNFo4VGNLY0tSOEpHWWQ3TXBZQ0EKWaL3yDFhmg0AvIRqFe50sM3xdK5HB9u8
        fpsZU1kSi23zed37WNLOKRmg42fqJ0sbe/jIJw0e6CvnOc4CLLreZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T00:46:12Z"
  mac: ENC[AES256_GCM,data:sO8RpGt0SkblqMVJLXHyt0pj+3OPpiYs37kpuoBggyxhCgexg5pUQPC4q3hiKKWWLo1lLWL8PFFjYYR6tedMoPAEVAc9UWNkT44FDjKARXm6vk9UPHzLM95jqsrFMj7+xRhgWpIjRynmcRhmkYIgAgGVExe22wgg2nB3xgXalOI=,iv:bQP3JNOxmQNpABsu4DLHgmPlvJXAEAuN1s3vGeCcMBA=,tag:IYS0XQj7Jqo48TyLste1GQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
